### ISSUE TITLE
emdfile issue, I install py4DSTEM version 0.14, but when I want to import py4DSTEM, it shows 'cannot import name 'RootedNode' from 'emdfile'. How can I solve this issue?

### ISSUE THREAD

**Issue by 1990-yang** [py4dstem/py4DSTEM_tutorials#19]

**Comment by FrancisBlackLee** [comment]
I got the same problem

**Comment by bsavitzky** [comment]
Hey @1990-yang @FrancisBlackLee - how did you install?

For now can you try going to the environment you installed in and running `pip install emdfile==0.0.8` and then see if the import will work?

**Comment by bsavitzky** [comment]
Ok, it looks most likely you did normal installations (either `pip install py4dstem` or `conda install py4dstem`), as I'm seeing this bug there.  It's now patched, but will likely take a few hours for that to propagate to conda.  If you did a conda install and don't want to wait, the simplest fix should be doing `pip install emdfile==0.0.8`, or you can re-install the package with `pip install py4dstem --upgrade`.

**Comment by FrancisBlackLee** [comment]
> Ok, it looks most likely you did normal installations (either `pip install py4dstem` or `conda install py4dstem`), as I'm seeing this bug there. It's now patched, but will likely take a few hours for that to propagate to conda. If you did a conda install and don't want to wait, the simplest fix should be doing `pip install emdfile==0.0.8`, or you can re-install the package with `pip install py4dstem --upgrade`.

`pip install emdfile==0.0.8` works for me, thanks!

**Comment by bsavitzky** [comment]
Great, thanks for letting me know.  @1990-yang Let me know if this solves the issue for you, and if so I'll close out the issue.  Thank you for finding the bug!

**Comment by 1990-yang** [comment]
> Yes, works for me! Thanks very much!

**Comment by bsavitzky** [comment]
Great :)
